chore: add gpg2 check to release workflow.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -44,8 +44,10 @@ jobs:
           # N.B. this is for debugging only.  TODO remove before release
           mvn -s ${{ vars.MAVEN_SETTINGS_FILE }} help:effective-settings
 
+          if ! command -v gpg2 &> /dev/null
+          then
+            echo "Failed to locate gpg2 on this host.  GPG2 is required to continue."
+            exit 1
+          fi
           
-          
-
-
-
+          gpg2 --version
